export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
